apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-postgres-deployment
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: {{ .Values.postgres.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
      name: postgres-pod
  template:
    metadata:
      labels:
        name: postgres-pod
        app: {{ .Values.appName }}
    spec:
      containers:
      - name: postgres
        image: {{ .Values.postgres.image }}
        env:
        - name: POSTGRES_USER
          value: {{ .Values.postgres.user }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.postgres.password }}
        - name: POSTGRES_HOST_AUTH_METHOD
          value: {{ .Values.postgres.authMethod }}
        ports:
        - containerPort: 5432
