apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-db
  labels:
    name: db-service
    app: {{ .Values.appName }}
spec:
  type: ClusterIP
  ports:
  - name: "db-service"
    port: 5432
    targetPort: 5432
  selector:
    app: {{ .Values.appName }}
    name: postgres-pod
