apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-redis-deployment
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: {{ .Values.redis.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
      name: redis-pod
  template:
    metadata:
      labels:
        name: redis-pod
        app: {{ .Values.appName }}
    spec:
      containers:
      - name: redis
        image: {{ .Values.redis.image }}
        ports:
        - containerPort: 6379
