apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-voting-service
  labels:
    name: voting-service
    app: {{ .Values.appName }}
spec:
  type: NodePort
  ports:
  - name: "voting-service"
    port: 81
    targetPort: 80
    nodePort: 30001
  selector:
    app: {{ .Values.appName }}
    name: voting-app-pod
